import os
import joblib
import pandas as pd
import warnings

# Suppress warnings to keep terminal output clean
warnings.filterwarnings("ignore")

# Dynamically locate the weights folder inside the installed package
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
WEIGHTS_DIR = os.path.join(BASE_DIR, 'weights')
MODEL_PATH = os.path.join(WEIGHTS_DIR, 'ccoligopred_binary_model.pkl')

def predict_binary(feature_df: pd.DataFrame) -> tuple:
    """
    Predicts Binary states (Trimer vs Non-Trimer) using the full feature set.
    Returns the predicted labels and the specific probability of the sequence being a Trimer.
    """
    
    # 1. Safely Load Model
    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(f"Missing binary model weight file: {MODEL_PATH}")
        
    model = joblib.load(MODEL_PATH)
    
    # 2. Predict (Binary uses all features generated by the RBF module)
    # We extract column 1 because binary predict_proba returns [Prob_Class_0, Prob_Class_1]
    preds_numeric = model.predict(feature_df)
    probs = model.predict_proba(feature_df)[:, 1] 
    
    # 3. Map numeric predictions to strings for user clarity
    preds_string = ["Trimer" if p == 1 else "Non-Trimer" for p in preds_numeric]
    
    # 4. Return as standard python lists to be unpacked by cli.py
    return preds_string, probs.tolist()