import os
import joblib
import pandas as pd

# Dynamically locate the weights folder inside the installed package
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
WEIGHTS_DIR = os.path.join(BASE_DIR, 'weights')
MODEL_PATH = os.path.join(WEIGHTS_DIR, 'oligocoil_binary_model.pkl')

def predict_binary(feature_df: pd.DataFrame) -> tuple:
    """Predicts Binary states (Trimer vs Non-Trimer) using the full feature set."""
    
    # 1. Load Model
    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(f"Missing model weight file: {MODEL_PATH}")
        
    model = joblib.load(MODEL_PATH)
    
    # 2. Predict (Binary uses all features generated by the RBF module)
    preds_numeric = model.predict(feature_df)
    probs = model.predict_proba(feature_df)[:, 1] # Probability of being a Trimer
    
    # Map numeric to strings for user clarity
    preds_string = ["Trimer" if p == 1 else "Non-Trimer" for p in preds_numeric]
    
    return preds_string, probs.tolist()
